{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-brocc
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - scikit-learn >=0.19.1
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - blast 2.6.0
    - vsearch
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_brocc
    - qiime2.plugins.brocc

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
